### ISSUE TITLE
Wrong rendering of text in GitBook PDFs

### ISSUE THREAD

**Issue by lwchkg** [lwchkg/gitbook-plugin-mathjax-commonhtml#2]

**Comment by lwchkg** [comment]
1. Positions of text in PDFs wrong. (CSS ignored.)
2. Size of text in display equations wrong. (Text is too large.)

![pdfxedit_2016-12-20_16-22-47](https://cloud.githubusercontent.com/assets/4113719/21343206/9e9a236a-c6d0-11e6-9ddd-ba6711dcee58.png)

**Comment by pkra** [comment]
For the font size, add

```css
.mjx-chtml {font-size: 2.26ex ! important}
.mjx-chtml .mjx-chtml {font-size: inherit ! important}
```

Cf. https://github.com/mathjax/MathJax-node/issues/204#issuecomment-208351504
